### ISSUE TITLE
Howto RL-013 raises an error and causes unit test error

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#382]
Howto RL-013 causes an error due to a missing module

![grafik](https://user-images.githubusercontent.com/79243976/185892614-7e654dbc-132c-46aa-89a3-f8671d9803d6.png)

Furthermore, it breaks the unit test run, when merging to main.

**Comment by rizkydiprasetya** [comment]
It is your python environment. You can just install it. The unit test says something else.

**Comment by detlefarend** [comment]
pip3 install transformations didn't work on my pc. More important is the ut error that rl-013 causes.

**Comment by rizkydiprasetya** [comment]
I will check

**Comment by detlefarend** [comment]
Thank you!

**Comment by rizkydiprasetya** [comment]
So, I have checked. Based on the MRO (Method Resolution Order) of HTMEnvModel, it calls Mode class first then Log class. I will check the HTMEnvModel.

**Comment by rizkydiprasetya** [comment]
@detlefarend done, should be fixed now.

**Comment by detlefarend** [comment]
Ok, great. I still have a local problem with package transformations but that's my challenge. Thanks for fixing!
