### ISSUE TITLE
Bug: Workflow Window/BoundaryDetector raises exception

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#753]
**1 Describe the bug**
I extended all howtos with task combination window+boundary detector as follows: I registered the _adapt_on_event method of the bd on the window for event Window.C_EVENT_DATA_REMOVED. Since then, the howtos

- **howto_oa_pp_004_rearranger_window_bd_normminmax_3d.py**
- **howto_oa_pp_005_rearranger_window_bd_normminmax_nd.py**

raise exceptions. I already tried to fix it and refactored method BoundaryDetector._adapt_on_event(). But this did not solve the problem. Interesting here: **howto_oa_pp_004_rearranger_window_bd_normminmax_2d.py** runs properly since refactoring...

Furthermore, I can not remember why we added a scaler functionality to the boundary detector.

**2 To Reproduce**
1. Run howto_oa_pp_004_rearranger_window_bd_normminmax_3d.py or howto_oa_pp_005_rearranger_window_bd_normminmax_nd.py

**3 Expected behavior**
Both howtos should not raise exceptions.

**4 Screenshots**

**5 Additional Informations**

5.1 Operating System
   - [X] Linux
   - [x] Windows
   - [ ] Mac OS

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , thanks for noticing the bug. It was a small bug with the creation of scaler array. I've fixed it.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, sry but I still get exceptions. Could you please check the howtos again? Thx!

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I just checked, after updating the latest merge commit. The howtos are still working fine in my system. What exception is it raising for you?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , Sorry, I forgot to answer about the scaler:
The scaler was to increase the boundaries by a factor of the detected boundaries. Thus, avoiding the repeated adaptations in a given region for smaller changes. However, this is optional, and is set to 1 by default.

**Comment by detlefarend** [comment]
> Hi @detlefarend , I just checked, after pulling the latest merge commit to my local. The howtos are still working fine in my system. What exception is it raising for you?

I am currently not on my pc. I have run the howtos under Linux with the latest version of numpy and matplotlib. Maybe thats the problem...

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I analyzed the problem further. It is a problem with the latest version of numpy. The howtos run properly in version 1.23.5.
